blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/ekstremedia/laravel-youtube/discussions
    about: Please ask and answer questions here.
  - name: Documentation
    url: https://github.com/ekstremedia/laravel-youtube#readme
    about: Read the documentation before opening an issue.